### ISSUE TITLE
how can i use this chart in my angular 2 project

### ISSUE THREAD

**Issue by karuppasamy20** [ZEPL/zeppelin-ultimate-line-chart#1]
how can i use this charts please answer me quick.

**Comment by aemelyanenko94** [comment]
are you serious? not answering for 5 months? there is no docs how to use this chart, wtf?

**Comment by Leemoonsoo** [comment]
Hi. This is visualization plugin for [Apache Zeppelin](https://zeppelin.apache.org). You can install and use the chart from 'Helium' menu on Apache Zeppelin > 0.8.0.

This chart is designed to work as a Zeppelin plugin. So i don't think using it in your project is simple like 'import and use'. You'll need to read and understand source code, and probably need to modify to use it in your project. Source code of this plugin is open.

Thanks for the interest and good luck.
